catalogo/urls.py
from django.urls import path
from django.conf.urls import url

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    #path('Hello/', views.hello, name='hello'),
    path('Productos/', views.ProductoListView.as_view(), name='Productos'),
    path('Producto/<int:pk>', views.ProductoDetailView.as_view(), name='Producto-detail'),
    path('Empresas/', views.EmpresaListView.as_view(), name='Empresas'),
    path('Empresa/<int:pk>',
         views.EmpresaDetailView.as_view(), name='Empresa-detail'),
]


urlpatterns += [
    path('myProductos/', views.LoanedProductosByUserListView.as_view(), name='my-borrowed'),
    path(r'borrowed/', views.LoanedProductosAllListView.as_view(), name='all-borrowed'),  # Added for challenge
]


# Add URLConf for librarian to renew a Producto.
urlpatterns += [
    path('Producto/<uuid:pk>/renew/', views.renew_Producto_librarian, name='renew-Producto-librarian'),
]


# Add URLConf to create, update, and delete Empresas
urlpatterns += [
    path('Empresa/create/', views.EmpresaCreate.as_view(), name='Empresa-create'),
    path('Empresa/<int:pk>/update/', views.EmpresaUpdate.as_view(), name='Empresa-update'),
    path('Empresa/<int:pk>/delete/', views.EmpresaDelete.as_view(), name='Empresa-delete'),
]

# Add URLConf to create, update, and delete Productos
urlpatterns += [
    path('Producto/create/', views.ProductoCreate.as_view(), name='Producto-create'),
    path('Producto/<int:pk>/update/', views.ProductoUpdate.as_view(), name='Producto-update'),
    path('Producto/<int:pk>/delete/', views.ProductoDelete.as_view(), name='Producto-delete'),
]

urlpatterns += [
    path('Productos/busqueda/<str:produc>', views.busqueda, name='busqueda'),
    path('Empresa/busqueda/<str:empr>', views.busqueda_empresa, name='busqueda_empresa'),
    path('ajax/search/', views.search, name='ajax-search'),
    path('pdf/descargar/', views.descargar, name='pdf-descargar'),

]

locall/urls.py
from django.urls import path
from django.contrib import admin

# Use include() to add URLS from the catalogo application and authentication system
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('catalogo/', include('catalogo.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalogo/', permanent=True)),
]



#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalogo/models.py
from django.db import models
from django.core.validators import RegexValidator
#from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

from django.urls import reverse  # To generate URLS by reversing URL patterns


class Categoria(models.Model):
    """Model representing a Producto categoria (e.g. Science Fiction, Non Fiction)."""
    nombre = models.CharField(
        max_length=50,
        help_text="Ingresa la categoria(p. ej. Salud, Universidades)"
        )

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.nombre


class Beneficio(models.Model):
    """Model representing a Beneficio (e.g. English, French, Japanese, etc.)"""
    nombre = models.CharField(max_length=200,
                            help_text="Ingresa el beneficio (p. ej. 10%)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.nombre


class Producto(models.Model):
    """Modelo que representa un servicio o producto"""
    nombre = models.CharField(max_length=100)
    empresa = models.ForeignKey('Empresa', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because producto can only have one empresa, but las empresas can have multiple productos
    # Empresa as a string rather than object because it hasn't been declared yet in file.
    descripcion = models.TextField(max_length=1000, help_text="Aquí puedes detallar las características del descuento o beneficio")

    categoria = models.ManyToManyField('Categoria', help_text="Escoge un categoria de este servicio o producto")
    # ManyToManyField used because a categoria can contain many Productos and a Producto can cover many categorias.
    # Categoria class has already been defined so we can specify the object above.
    beneficio = models.ForeignKey('Beneficio', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['nombre', 'empresa']

    def display_categoria(self):
        """Creates a string for the Categoria. This is required to display categoria in Admin."""
        return ', '.join([categoria.nombre for categoria in self.categoria.all()[:3]])

    display_categoria.short_description = 'Categoría'

    def get_absolute_url(self):
        """Returns the url to access a particular Producto instance."""
        return reverse('Producto-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.nombre


import uuid  # Required for unique Producto instances
from datetime import date

from django.contrib.auth.models import User  # Required to assign User as a propietario


class ProductoInstance(models.Model):
    #Model representing a specific copy of a Producto (i.e. that can be borrowed from the library).
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular Producto across whole library")
    Producto = models.ForeignKey('Producto', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    propietario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text=('Producto availability')
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set Producto as returned"),)

    def __str__(self):
        #String for representing the Model object.
        return '{0} ({1})'.format(self.id, self.Producto.nombre)



class Empresa(models.Model):
    """Model representing an Empresa."""
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    telRegex = RegexValidator(regex = r"^\+?1?\d{10,15}$")
    telefono = models.CharField(validators = [telRegex], max_length = 16, unique = True,
                            help_text="Ingresa el teléfono a 10 dígitos")

    email = models.EmailField('email', null=True, blank=True)
    facebook = models.CharField(max_length=50, null=True, blank=True)
    webRegex = RegexValidator(regex = r"^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$")
    web = models.CharField(validators = [webRegex], max_length=50, null=True, blank=True)

    class Meta:
        ordering = ['nombre', 'descripcion']

    def get_absolute_url(self):
        """Returns the url to access a particular Empresa instance."""
        return reverse('Empresa-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.nombre, self.descripcion)

catalogo/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime  # for checking renewal date range.

from django import forms


class RenewProductoForm(forms.Form):
    """Form for a librarian to renew Productos."""
    renewal_date = forms.DateField(
            help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        # Check date is in range librarian allowed to change (+4 weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

catalogo/templates/catalogo/descarga.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<div class="row center-align">
  <div class="col s5">
    <a href="#" class="brand-logo"><img class="responsive-img" style="width=60%;height=60%;" alt="" src="{% static 'images/logo.png' %}"></a>
  </div>
  <div class="col s5">
<div class="card center-align blue darken-4">

<div class="card-content blue-text darken-4">
  <span class="card-title black-text"></span>
    <ul>
      <li>
        <a href="{% static 'pdf/catalogo-yo-brillo-con-morelia.pdf' %}" class="btn btn-primary btn-sm" target="_blank">Ver catálogo</a>
      </li>


    </ul>
  </div>
  </div>
  </div>
  <div class="col s2"></div>
  </div>


{% endblock %}

catalogo/templates/catalogo/empresa_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Borra Empresa</h1>

<p>Seguro de borrar la Empresa: {{ empresa }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalogo/templates/catalogo/empresa_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col s2"></div>
  <div class="col s8">
<div class="card center-align white">

<div class="card-content blue-text darken-4">
  <span class="card-title black-text">{{ empresa.nombre }}</span>
  <div class="section">
<p>{{empresa.descripcion}}</p>
<p>{% if empresa.direccion %}Dirección: {{empresa.direccion}}{% endif %}</p>
<p>{% if empresa.telefono %}Teléfono: {{empresa.telefono}}{% endif %}</p>
<p>{% if empresa.email %}Coreo: {{empresa.email}}{% endif %}</p>
<p>{% if empresa.facebook %}Facebook: {{empresa.facebook}}{% endif %}</p>
<p>{% if empresa.web %}Sitio web:{{empresa.web}}{% endif %}</p>
</div>
<div class="divider"></div>
<div class="section">
<div style="margin-left:20px;margin-top:20px">
<span class="card-title black-text">Beneficios:</span>
<ul>
{% for producto in empresa.producto_set.all %}
  <li><a href="{% url 'Producto-detail' producto.pk %}">{{producto}}</a></li>
  <li>{{producto.descripcion}}</li>
{% endfor %}
</ul>
</div>
</div>

</div>
</div>
</div>
<div class="col s2"></div>
</div>
{% endblock %}

catalogo/templates/catalogo/empresa_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalogo/templates/catalogo/empresa_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col s1"></div>
  <div class="col s10">
<div class="card">

<div class="card-content blue-text darken-4">
  <span class="card-title black-text">Listado de Empresas Participantes</span>


{% if empresa_list %}
  <ul>

  {% for empresa in empresa_list %}
    <div class="section">
      <a href="{{ empresa.get_absolute_url }}">
      {{ empresa }}</a>
      ({% if empresa.telefono %}Tel: {{empresa.telefono}}{% endif %})

    </div>
    <div class="divider"></div>
  {% endfor %}

 </ul>
{% else %}
  <p>No hay empresas registradas.</p>
{% endif %}
</div>
</div>
</div>
<div class="col s1"></div>
</div>


{% endblock %}

catalogo/templates/catalogo/producto_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Borrar Producto</h1>

<p>Seguro de borrar este Producto?: {{ producto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalogo/templates/catalogo/producto_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col s2"></div>
  <div class="col s8">
<div class="card center-align white">

<div class="card-content blue-text darken-4">
  <span class="card-title black-text">{{ producto.nombre }}</span>
  <div class="section">


<p><strong>Empresa:</strong> <a href="{{ producto.empresa.get_absolute_url }}">{{ producto.empresa }}</a></p>
<p><strong>Descripcion:</strong> {{ producto.descripcion }}</p>
<p><strong>Beneficio:</strong> {{ producto.beneficio }}</p>
<p><strong>Categoria:</strong> {{ producto.categoria.all|join:", " }}</p>

</div>
<div class="divider"></div>

</div>
</div>
</div>
<div class="col s2"></div>
</div>
{% endblock %}

catalogo/templates/catalogo/producto_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalogo/templates/catalogo/producto_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col s1"></div>
  <div class="col s10">
<div class="card">

<div class="card-content blue-text darken-4">
  <span class="card-title black-text">Listado de Beneficios</span>
    {% if producto_list %}
    <ul>

      {% for producto in producto_list %}


      <div class="section">
        <a href="{{ producto.get_absolute_url }}">{{ producto.nombre }}</a> ({{producto.empresa}})
      </div>
      <div class="divider"></div>
      {% endfor %}

    </ul>

    {% else %}
      <p>No hay productos registrados</p>
    {% endif %}
  </div>
  </div>
  </div>
  <div class="col s1"></div>
  </div>

{% endblock %}

catalogo/templates/catalogo/producto_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Renew: {{Producto_instance.Producto.title}}</h1>
    <p>Borrower: {{Producto_instance.borrower}}</p>
    <p{% if Producto_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{Producto_instance.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalogo/templates/catalogo/productoinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Productos</h1>

    {% if Productoinstance_list %}
    <ul>

      {% for Productoinst in Productoinstance_list %} 
      <li class="{% if Productoinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'Producto-detail' Productoinst.Producto.pk %}">{{Productoinst.Producto.title}}</a> ({{ Productoinst.due_back }}) {% if user.is_staff %}- {{ Productoinst.borrower }}{% endif %} {% if perms.catalogo.can_mark_returned %}- <a href="{% url 'renew-Producto-librarian' Productoinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no Productos borrowed.</p>
    {% endif %}       
{% endblock %}

catalogo/templates/catalogo/productoinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed Productos</h1>

    {% if Productoinstance_list %}
    <ul>

      {% for Productoinst in Productoinstance_list %} 
      <li class="{% if Productoinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'Producto-detail' Productoinst.Producto.pk %}">{{Productoinst.Producto.title}}</a> ({{ Productoinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no Productos borrowed.</p>
    {% endif %}       
{% endblock %}